"""Change confirm_status from Boolean to String in Question table

Revision ID: 1a0b52e8fb28
Revises: 08f9494d0e92
Create Date: 2024-08-26 19:30:01.570877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a0b52e8fb28'
down_revision = '08f9494d0e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('print_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('confirm_status', sa.String(length=20), nullable=False))
        batch_op.drop_column('is_approved')
        batch_op.drop_column('status')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('confirm_status')
        batch_op.drop_column('print_status')

    # ### end Alembic commands ###
