"""Add credit_hours to Course model

Revision ID: ee2207fb6f22
Revises: 0d379aed687a
Create Date: 2024-08-22 02:52:26.539637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee2207fb6f22'
down_revision = '0d379aed687a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_hours', sa.Integer(), nullable=False))

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('start', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('venue', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('examiner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['examiner_id'], ['id'])
        batch_op.drop_column('details')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', mysql.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('examiner_id')
        batch_op.drop_column('venue')
        batch_op.drop_column('end')
        batch_op.drop_column('start')
        batch_op.drop_column('title')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('credit_hours')

    # ### end Alembic commands ###
